name: add_mermaid_link

on:
  push:
    branches:
      - "feature/**"

jobs:
  add_mermaid_link:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Run Python
        run: |
          cd .github/workflows/add_meraid_link
          python .github/workflows/add_meraid_link/main.py "${{ github.repository }}" "${{ github.ref_name }}"
      # - name: Run Git
      #   run: |
      #     git config --global user.name "lop9940"
      #     git config --global user.email "qaqclop9940@gmail.com"
      #     git add .
      #     git commit -m "Update by GitHub Action"
      #     git push