name: link_fix

on:
  push:
    branches:
      - "feature/**"

  workflow_dispatch:

jobs:
  py-test:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Run Python
        run: python .github/workflows/script/link_fix.py
      - name: Run Git
        run: |
          git config --global user.name "lop9940"
          git config --global user.email "qaqclop9940@gmail.com"
          git add .
          git commit -m "Update by GitHub Action"
          git push